import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useContractRead } from "wagmi";
import blogABI from "../../artifacts/contracts/Blog.sol/Blog.json";
import { ownerAddress, contractAddress } from "../config";

const Home: NextPage = () => {
  console.log("hey");
  const { data, isLoading, isError } = useContractRead({
    addressOrName: contractAddress,
    contractInterface: blogABI.abi,
    functionName: "fetchPosts",
  });

  const router = useRouter();

  const handleClick = async () => {
    router.push("/post");
  };

  isLoading && <p>Loading...</p>;

  console.log(data);
  return (
    <div className="">
      <Head>
        <title>Web3 Mirror</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="text-3xl font-bold">Mirror</div>
      {data?.slice(1).map((post, i) => (
        <Link href={`/post/${post[2]}`} key={i}>
          <p>{post[1]}</p>
        </Link>
      ))}

      <div>
        <button className="flex items-center" onClick={handleClick}>
          <span>Create post</span>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            className="h-4 w-5"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            strokeWidth={2}
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M9 5l7 7-7 7"
            />
          </svg>
        </button>
      </div>
    </div>
  );
};

export default Home;
